#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Vercel } from '@vercel/sdk';

const appRoot = resolve(fileURLToPath(new URL('..', import.meta.url)));
const workspaceRoot = resolve(appRoot, '..');

const usage = `
Usage:
  node scripts/configure-app-env.mjs --mode local --api-url http://192.168.240.1:3000
  VERCEL_TOKEN=... node scripts/configure-app-env.mjs --mode prod --api-url https://api.example.com

Options:
  --mode local|prod              Defaults to local.
  --api-url URL                  API base URL to bake into the Expo bundle.
  --environment production|...   Vercel env target for prod mode. Defaults to production.
  --vercel-project PATH          Next/Vercel project root. Defaults to ../hackatao.
  --output PATH                  Env file to write. Defaults to .env.local.
`;

const args = process.argv.slice(2);

const readArg = (name, fallback) => {
  const index = args.indexOf(name);
  if (index === -1) {
    return fallback;
  }

  return args[index + 1] ?? fallback;
};

const hasFlag = (name) => args.includes(name);

if (hasFlag('--help') || hasFlag('-h')) {
  console.log(usage.trim());
  process.exit(0);
}

const mode = readArg('--mode', 'local');
const environment = readArg('--environment', 'production');
const outputPath = resolve(appRoot, readArg('--output', '.env.local'));
const vercelProjectRoot = resolve(workspaceRoot, readArg('--vercel-project', 'hackatao'));
const requestedApiUrl = readArg('--api-url', process.env.EXPO_PUBLIC_API_BASE_URL);

const assertUrl = (value, label) => {
  if (!value) {
    throw new Error(`${label} is required.`);
  }

  try {
    return new URL(value).origin;
  } catch {
    throw new Error(`${label} must be a valid URL.`);
  }
};

const readVercelProject = async () => {
  const projectPath = join(vercelProjectRoot, '.vercel', 'project.json');
  const project = JSON.parse(await readFile(projectPath, 'utf8'));

  if (!project.projectId || !project.orgId) {
    throw new Error(`Invalid Vercel project file: ${projectPath}`);
  }

  return project;
};

const targetIncludes = (target, expected) => {
  if (Array.isArray(target)) {
    return target.includes(expected);
  }

  return target === expected;
};

const getEnvValue = (envs, key, target) => {
  const match = envs.find((env) => env.key === key && targetIncludes(env.target, target));
  return match?.value?.trim();
};

const getProdConfig = async () => {
  const token = process.env.VERCEL_TOKEN?.trim();

  if (!token) {
    throw new Error('VERCEL_TOKEN is required for --mode prod.');
  }

  const project = await readVercelProject();
  const vercel = new Vercel({ bearerToken: token });
  const response = await vercel.projects.filterProjectEnvs({
    idOrName: project.projectId,
    teamId: project.orgId,
    decrypt: 'true',
  });
  const envs = response.envs ?? [];
  const apiUrl =
    requestedApiUrl ??
    getEnvValue(envs, 'EXPO_PUBLIC_API_BASE_URL', environment) ??
    getEnvValue(envs, 'NEXT_PUBLIC_APP_URL', environment);

  return {
    apiUrl: assertUrl(apiUrl, 'API URL'),
  };
};

const getLocalConfig = () => ({
  apiUrl: assertUrl(requestedApiUrl ?? 'http://192.168.240.1:3000', 'API URL'),
});

const quoteEnv = (value) => JSON.stringify(value);

const writeExpoEnv = async ({ apiUrl }) => {
  const lines = [
    '# Generated by scripts/configure-app-env.mjs',
    `EXPO_PUBLIC_API_BASE_URL=${quoteEnv(apiUrl)}`,
    '',
  ];

  await writeFile(outputPath, lines.join('\n'));
  console.log(`Wrote ${outputPath}`);
  console.log(`EXPO_PUBLIC_API_BASE_URL=${apiUrl}`);
};

if (mode !== 'local' && mode !== 'prod') {
  throw new Error(`Unknown mode: ${mode}`);
}

await writeExpoEnv(mode === 'prod' ? await getProdConfig() : getLocalConfig());
